import os

def export_codebase(output_file="codebase_export.txt"):
    """
    Traverses the project directory and aggregates source files into a single text file.
    Filters out binary files, large directories, and non-essential files to keep the
    context lean for AI ingestion.
    """
    # Configuration
    ALLOWED_EXTENSIONS = {".py", ".md", ".html", ".js", ".css", ".json", ".sh", ".txt", ".ini", ".conf", ".toml", ".pdf", ".epub"}

    EXCLUDED_DIRS = {
        ".git",
        "venv",
        "env",
        ".venv",
        "node_modules",
        "__pycache__",
        "cache",
        "ephe",
        "database",
        "anki_decks",
        "sanskrit_texts",
        "staticfiles",
        ".idea",
        ".pytest_cache",
        ".ruff_cache",
        "backups",
        ".gemini",
    }

    EXCLUDED_FILES = {
        "codebase_export.txt",
        "commits_export.txt",
        "commits_export.md",
        "package-lock.json",
        "yarn.lock",
        ".env",
        ".DS_Store",
        "server.log",
        "server.pid",
        "va_text.txt"
    }

    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    output_path = os.path.join(project_root, output_file)

    with open(output_path, "w", encoding="utf-8") as out:
        out.write("# PROJECT CODEBASE EXPORT\n")
        out.write("# Generated by export_codebase.py\n\n")

        for root, dirs, files in os.walk(project_root):
            # Prune excluded directories in-place to prevent os.walk from entering them
            dirs[:] = [d for d in dirs if d not in EXCLUDED_DIRS]

            for file in sorted(files):
                if file in EXCLUDED_FILES:
                    continue

                # Skip minified files
                if file.endswith(".min.js") or file.endswith(".min.css"):
                    continue
                
                if file.endswith("-lock.json"):
                    continue

                _, ext = os.path.splitext(file)
                if ext.lower() not in ALLOWED_EXTENSIONS:
                    continue

                full_path = os.path.join(root, file)
                relative_path = os.path.relpath(full_path, project_root)
                
                # Check file size (skip files larger than 5MB to allow the PDF and EPUB to be processed)
                if os.path.getsize(full_path) > 5 * 1024 * 1024:
                    print(f"Skipping {relative_path} (too large: {os.path.getsize(full_path)} bytes)")
                    continue

                try:
                    content = ""
                    if ext.lower() == ".pdf":
                        import subprocess
                        # Only extract text if pdftotext is available
                        try:
                            result = subprocess.run(['pdftotext', full_path, '-'], capture_output=True, text=True, check=True)
                            content = result.stdout
                            if not content.strip():
                                print(f"Skipping {relative_path} (No extractable text found in PDF)")
                                continue
                        except Exception as e:
                            print(f"Skipping {relative_path} (Error extracting PDF text: {e})")
                            continue
                    elif ext.lower() == ".epub":
                        import zipfile
                        import re
                        try:
                            with zipfile.ZipFile(full_path, 'r') as epub:
                                for item in epub.namelist():
                                    if item.endswith('.xhtml') or item.endswith('.html'):
                                        raw_html = epub.read(item).decode('utf-8')
                                        # Very simple regex to strip HTML tags
                                        text = re.sub(r'<[^>]+>', ' ', raw_html)
                                        content += text + "\n"
                        except Exception as e:
                            print(f"Skipping {relative_path} (Error extracting EPUB text: {e})")
                            continue
                    else:
                        with open(full_path, encoding="utf-8") as f:
                            content = f.read()

                    # Write separator and header
                    out.write("=" * 80 + "\n")
                    out.write(f"FILE: {relative_path}\n")
                    out.write("=" * 80 + "\n")
                    out.write(content)
                    out.write("\n\n")

                    print(f"Exported: {relative_path}")
                except Exception as e:
                    print(f"Error reading {relative_path}: {e}")

    # Check file size of the output
    size_mb = os.path.getsize(output_path) / (1024 * 1024)
    print(f"\nSuccessfully generated: {output_file}")
    print(f"Total size: {size_mb:.2f} MB")

if __name__ == "__main__":
    export_codebase()
